cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    hoangtq15:
      email: hoangtq15@fpt.com
      name: Hoang Truong Quang
      password: $2b$12$ADGNqumL/Fu5.IdwYthslu16HJYb/dDq0SDISkE137aWXTmGnPJGS
    longld11:
      email: longld11@fpt.com
      name: Long LD
      password: $2b$12$UtZE/z2EJpc9LTdHa78SIe8iHHg9AcldepQ5LP5HV.fqYH5HZ1zDu
    quang1210:
      email: quangvm9@fpt.com.vn
      name: CDP PGP
      password: $2b$12$8W.JDpcrbGqqtiVvIL0qdu1YWS89qaE69GXdeJHsCPyw45xOVUPI2
    quang_vuminh:
      email: quang.vuminh@hcmut.edu.vn
      name: quangvm9
      password: $2b$12$pcV7p/taxjIOvkowT5Zzlu12P9vQTp6Jd6u9Bta18Vm7OHfwgmvau
    quangvm9:
      email: quangvm9@fpt.com
      name: Quang Vu Minh
      password: $2b$12$EELDil4tO69GMOkBD4P0MesYyicJbEeqNFJeAn00F9L3CKRKooQuC
    user1:
      email: user1@gmail.com
      name: User 1
      password: $2b$12$C1X9PjI/k1fGxHa48z/2i.FKEUMpSl/JW6s06CeAyBrKrQeNmhEQy
    user2:
      email: user2@gmail.com
      name: User 2
      password: $2b$12$8.yOMdm.sWWVUQzZkf.52O0BJGGExvR9w5R1.8sTTCqde5OSgWC2q
    user3:
      email: user3@gmail.com
      name: User 3
      password: $2b$12$GLWgOcotOtkh72dy12plI.IaLsd3XTqsmj08SqbDeVI13MjqeTOue
    user4:
      email: user4@gmail.com
      name: User 4
      password: $2b$12$xtMf6sRhGjw5QexJg4WwXutdGeJopVGGKPs87stHeqJicqmq7tj/.
    user5:
      email: user5@gmail.com
      name: User 5
      password: $2b$12$z.7jlxCCFFvqiIg8BvV3B./5XG8jON0v6IxlWxCSqwnIc2lHlWpfW
    user6:
      email: user6@gmail.com
      name: User 6
      password: $2b$12$vB/tIWjNXy8VYFR1miW0J.HugOilbHTOy3XN13Q4yehNsxS3.xVG2
    user_test1:
      email: user_test1@gmail.com
      name: User Test 1
      password: $2b$12$WkjWi9ICYsUZMx8dCxIlF.bx0Ko38YyjYcpnIJ3zyMLbuqM4bL4lq
    user_test2:
      email: user_test2@gmail.com
      name: User Test 2
      password: $2b$12$mpNyPO/mAzWc6v9YGw95bOyZfRD/FQnhv0S2N41HVL5.xghvS19E2
preauthorized:
  emails:
  - quangvm9@fpt.com.vn
