cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    hoangtq15:
      email: hoangtq15@fpt.com
      name: Hoang Truong Quang
      password: $2b$12$ADGNqumL/Fu5.IdwYthslu16HJYb/dDq0SDISkE137aWXTmGnPJGS
    longld11:
      email: longld11@fpt.com
      name: Long LD
      password: $2b$12$UtZE/z2EJpc9LTdHa78SIe8iHHg9AcldepQ5LP5HV.fqYH5HZ1zDu
    quang1210:
      email: quangvm9@fpt.com.vn
      name: CDP PGP
      password: $2b$12$8W.JDpcrbGqqtiVvIL0qdu1YWS89qaE69GXdeJHsCPyw45xOVUPI2
    quang_vuminh:
      email: quang.vuminh@hcmut.edu.vn
      name: quangvm9
      password: $2b$12$pcV7p/taxjIOvkowT5Zzlu12P9vQTp6Jd6u9Bta18Vm7OHfwgmvau
    quangvm9:
      email: quangvm9@fpt.com
      name: Quang Vu Minh
      password: $2b$12$EELDil4tO69GMOkBD4P0MesYyicJbEeqNFJeAn00F9L3CKRKooQuC
preauthorized:
  emails:
  - quangvm9@fpt.com.vn
